CREATE TABLE users (
userId VARCHAR(255) NOT NULL UNSIGNED PRIMARY KEY,
pass VARCHAR(30) NOT NULL,
username VARCHAR(30) NOT NULL
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(50) NOT NULL
birthday DATE,
Created_at DATE
)
CREATE TABLE Cart (
idCart VARCHAR(255) NOT NULL UN  PRIMARY KEY,
nameShoes VARCHAR(30) NOT NULL,
image VARCHAR(255) NOT NULL,
price decimal(15,2) NOT NULL,
)
CREATE TABLE product (
id VARCHAR(255) NOT NULL   PRIMARY KEY,
nameShoes VARCHAR(30) NOT NULL,
image VARCHAR(255) NOT NULL,
price decimal(15,2) NOT NULL,
count INT 
)